CREATE DATABASE entregable1;

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "email" text NOT NULL,
  "password" text NOT NULL,
  "age" int,
  "role_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "description" text,
  "level_id" int NOT NULL,
  "teacher_id" int NOT NULL,
  "categorie_id" int NOT NULL
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL
);

CREATE TABLE "users_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "teachers_courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "teacher_id" int NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "courses_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "url" text NOT NULL,
  "course_id" int NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("categorie_id") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_id") REFERENCES "level" ("id");

ALTER TABLE "courses_videos" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "teachers_courses" ADD FOREIGN KEY ("teacher_id") REFERENCES "users" ("id");

ALTER TABLE "teachers_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

INSERT INTO categories (name) VALUES ('frontend'), ('backend');

INSERT INTO level (name) VALUES ('beginner'), ('intermediate'), ('advanced');

INSERT INTO roles (name) VALUES ('student'), ('teacher'), ('admin');

INSERT INTO users (name, email, password, age, role_id) VALUES ('Sebastian Martinez', 'sm@mail.com', 'sm12345', 28, 1), ('Marcelo Vinicio', 'mv@mail.com', 'mv12345', 25, 1), ('Adan Gomez', 'ag@mail.com', 'ag12345', 27, 1),('Daniel Santoyo', 'ds@mail.com', 'ds12345', 30, 1), ('YUtany Barreto', 'yb@mail.com', 'yb12345', 32, 1), ('Brenda Gonzalez', 'bg@mail.com', 'bg12345', 31, 2), ('Ian Rosas', 'ir@mail.com', 'ir12345', 33, 2), ('Pedro Romano', 'pr@mail.com', 'pr12345', 29, 3);

INSERT INTO courses (title, description, level_id, teacher_id, categorie_id) VALUES ('HTML', 'HTML course', 1, 6, 1), ('CSS', 'CSS course', 1, 6, 1), ('Sass', 'Sass course', 1, 6, 1), ('JavaScript', 'JavaScript course', 1, 6, 1), ('React', 'React course', 2, 6, 1), ('TypeScript', 'TypeScript course', 2, 7, 1), ('SQL', 'SQL course', 2, 7, 2), ('Node', 'Node course', 3, 7, 2), ('Mongo', 'Mongo course', 3, 7, 2);

INSERT INTO courses_videos (title, url, course_id) VALUES ('HTML1', 'link1', 2), ('HTML2', 'link2', 2), ('CSS1', 'link3', 3), ('CSS2', 'link4', 3), ('Sass', 'link5', 4), ('JavaScript1', 'link6', 5), ('JavaScript2', 'link7', 5), ('React1', 'link8', 6), ('React2', 'link9', 6), ('TypeScript', 'link10', 7), ('SQL', 'link11', 8), ('Node', 'link12', 9), ('Mongo', 'link13', 10);

INSERT INTO users_courses (user_id, course_id) VALUES (1, 2), (1, 3), (2, 4), (2, 5), (3, 6), (4, 7), (5, 6), (5, 7);